/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HaslinAvila_Lab8;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Fiery_000
 */
public class Frame_Principal extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Frame_Principal() {
        initComponents();
        this.setLocationRelativeTo(this);
        cont = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AgregarEM = new javax.swing.JDialog();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_nombreH = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf_alturaH = new javax.swing.JTextField();
        tf_edadH = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tf_saludH = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tf_poderH = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tf_salarbolH = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tf_nombreL = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tf_alturaL = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tf_edadL = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tf_saludL = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tf_poderL = new javax.swing.JTextField();
        tf_branquias = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tf_aleta = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        tf_nombreSS = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        tf_alturaSS = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        tf_edadSS = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        tf_saludSS = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        tf_poderSS = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        tf_alasSS = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        tf_nombreS = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        tf_alturaS = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        tf_edadS = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        tf_saludS = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        tf_poderS = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        tf_alasS = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_modHadas = new javax.swing.JList();
        tf_aleta1 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        tf_branquias1 = new javax.swing.JTextField();
        cb_hadas = new javax.swing.JComboBox();
        jLabel35 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        tf_alas1 = new javax.swing.JTextField();
        tf_nombre1 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        tf_altura1 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        tf_edad1 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_ElimHadas = new javax.swing.JList<>();
        cb_hadas1 = new javax.swing.JComboBox();
        jButton8 = new javax.swing.JButton();
        Simulacion = new javax.swing.JDialog();
        cb_hada1 = new javax.swing.JComboBox<>();
        pb_player1 = new javax.swing.JProgressBar();
        cb_hada2 = new javax.swing.JComboBox<>();
        pb_player2 = new javax.swing.JProgressBar();
        jButton9 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 204));
        jLabel1.setText("--HAMADRIADES--");

        jLabel2.setText("Nombre");

        jLabel3.setText("Edad");

        jLabel4.setText("Altura");

        jLabel5.setText("Salud");

        tf_saludH.setEditable(false);
        tf_saludH.setText("373");

        jLabel6.setText("Poder");

        tf_poderH.setEditable(false);
        tf_poderH.setText("78");

        jLabel7.setText("Salud Arbol");

        tf_salarbolH.setEditable(false);
        tf_salarbolH.setText("173");

        jButton3.setText("AGREGAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jLabel1))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(tf_saludH, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tf_poderH, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tf_nombreH, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tf_edadH, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tf_alturaH, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_salarbolH, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_nombreH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(tf_alturaH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_edadH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_poderH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(tf_saludH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tf_salarbolH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jButton3)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Hamadriades", jPanel6);

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 0, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 204, 51));
        jLabel8.setText("--LAMIA--");

        jLabel9.setText("Nombre");

        jLabel10.setText("Altura");

        jLabel11.setText("Edad");

        jLabel12.setText("Salud");

        tf_saludL.setEditable(false);
        tf_saludL.setText("475");

        jLabel13.setText("Poder");

        tf_poderL.setEditable(false);
        tf_poderL.setText("57");

        jLabel14.setText("Branquias");

        jLabel15.setText("Aleta");

        jButton4.setText("AGREGAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(jLabel8))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel15)
                            .addComponent(jLabel11)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(tf_saludL, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_poderL, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_nombreL, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_edadL, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_aleta, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tf_alturaL, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2))
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tf_branquias, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tf_nombreL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(tf_alturaL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_edadL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tf_poderL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(tf_saludL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tf_aleta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(tf_branquias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Lamias", jPanel7);

        jLabel16.setFont(new java.awt.Font("Comic Sans MS", 0, 15)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 0, 0));
        jLabel16.setText("--SALAMANDRAS--");

        jLabel27.setText("Nombre");

        jLabel26.setText("Altura");

        jLabel28.setText("Edad");

        jLabel29.setText("Salud");

        tf_saludSS.setEditable(false);
        tf_saludSS.setText("683");

        jLabel30.setText("Poder");

        tf_poderSS.setEditable(false);
        tf_poderSS.setText("71");

        jLabel31.setText("Alas");

        jButton5.setText("AGREGAR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(jLabel16))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel27))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addComponent(tf_saludSS, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40)
                                        .addComponent(jLabel30)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tf_poderSS, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tf_nombreSS, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tf_edadSS, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel26)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tf_alturaSS, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel31)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_alasSS, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(tf_nombreSS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(tf_alturaSS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_edadSS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(tf_poderSS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(tf_saludSS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_alasSS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31))
                .addGap(39, 39, 39)
                .addComponent(jButton5)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Salamandras", jPanel8);

        jLabel21.setFont(new java.awt.Font("Comic Sans MS", 0, 15)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 153, 255));
        jLabel21.setText("--SILFIDES--");

        jLabel18.setText("Nombre");

        jLabel20.setText("Altura");

        jLabel19.setText("Edad");

        jLabel22.setText("Salud");

        tf_saludS.setEditable(false);
        tf_saludS.setText("563");

        jLabel23.setText("Poder");

        tf_poderS.setEditable(false);
        tf_poderS.setText("67");

        jLabel24.setText("Alas");

        jButton6.setText("AGREGAR");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(jLabel21))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel22)
                            .addComponent(jLabel19)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel9Layout.createSequentialGroup()
                                    .addComponent(tf_saludS, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(40, 40, 40)
                                    .addComponent(jLabel23)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tf_poderS, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel9Layout.createSequentialGroup()
                                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tf_nombreS, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tf_edadS, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel20)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tf_alturaS, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(tf_alasS, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(tf_nombreS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(tf_alturaS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_edadS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(tf_poderS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(tf_saludS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(tf_alasS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jButton6)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Silfides", jPanel9);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Agregar", jPanel3);

        jLabel37.setText("Aleta");

        jPanel12.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 3, 2, 3, new java.awt.Color(255, 0, 0)));

        jl_modHadas.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jl_modHadasValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jl_modHadas);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel38.setText("Branquias");

        cb_hadas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Lamias", "Hamadriades", "Silfides", "Salamandras" }));
        cb_hadas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_hadasItemStateChanged(evt);
            }
        });

        jLabel35.setText("Alas");

        jLabel32.setText("Nombre");

        jButton7.setText("MODIFICAR");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel33.setText("Altura");

        jLabel34.setText("Edad");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel34)
                                .addGap(18, 18, 18)
                                .addComponent(tf_edad1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel32)
                                .addGap(18, 18, 18)
                                .addComponent(tf_nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                            .addGap(5, 5, 5)
                            .addComponent(jLabel33)
                            .addGap(18, 18, 18)
                            .addComponent(tf_altura1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel37)
                                .addGap(18, 18, 18)
                                .addComponent(tf_aleta1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel38)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_branquias1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addComponent(jLabel35)
                            .addGap(18, 18, 18)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tf_alas1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cb_hadas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cb_hadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel32)
                            .addComponent(tf_nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel33)
                            .addComponent(tf_altura1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_edad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel34))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel37)
                            .addComponent(tf_aleta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel38)
                            .addComponent(tf_branquias1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_alas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel35))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Modificar", jPanel4);

        jPanel11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));

        jScrollPane2.setViewportView(jl_ElimHadas);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                .addContainerGap())
        );

        cb_hadas1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Lamias", "Hamadriades", "Silfides", "Salamandras" }));
        cb_hadas1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_hadas1ItemStateChanged(evt);
            }
        });

        jButton8.setText("ELIMINAR");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(cb_hadas1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(161, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(162, 162, 162))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(cb_hadas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jButton8)
                .addGap(27, 27, 27))
        );

        jTabbedPane1.addTab("Eliminar", jPanel5);

        javax.swing.GroupLayout AgregarEMLayout = new javax.swing.GroupLayout(AgregarEM.getContentPane());
        AgregarEM.getContentPane().setLayout(AgregarEMLayout);
        AgregarEMLayout.setHorizontalGroup(
            AgregarEMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarEMLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        AgregarEMLayout.setVerticalGroup(
            AgregarEMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarEMLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pb_player1.setForeground(new java.awt.Color(204, 0, 0));
        pb_player1.setValue(100);
        pb_player1.setString("100%");
        pb_player1.setStringPainted(true);

        pb_player2.setForeground(new java.awt.Color(204, 0, 0));
        pb_player2.setValue(100);
        pb_player2.setString("100%");
        pb_player2.setStringPainted(true);

        jButton9.setText("BATTLE START!!");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SimulacionLayout = new javax.swing.GroupLayout(Simulacion.getContentPane());
        Simulacion.getContentPane().setLayout(SimulacionLayout);
        SimulacionLayout.setHorizontalGroup(
            SimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SimulacionLayout.createSequentialGroup()
                .addGroup(SimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SimulacionLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(SimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cb_hada1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pb_player1, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
                            .addComponent(cb_hada2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pb_player2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(SimulacionLayout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        SimulacionLayout.setVerticalGroup(
            SimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SimulacionLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(cb_hada1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pb_player1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jButton9)
                .addGap(42, 42, 42)
                .addComponent(cb_hada2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pb_player2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 0), 3, true));

        jButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton1.setText("S I M U L A C I O N");
        jButton1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jButton1StateChanged(evt);
                jButton1StateChanged2(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 0), 3, true));

        jButton2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton2.setText("Agregar Hadas");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenu1.setText("Opciones");

        jMenuItem1.setText("Abrir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Guardar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Guardar Como");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Salir");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setText("About");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.AgregarEM.setModal(true);
        this.AgregarEM.pack();
        this.AgregarEM.setLocationRelativeTo(this);
        this.AgregarEM.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.Simulacion.setModal(true);
        this.Simulacion.pack();
        this.Simulacion.setLocationRelativeTo(this);
        this.Simulacion.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int salud = 373, poder = 78, salArbol = 173;
        try {
            hamadriade.add(new Hamadriades(salArbol, tf_nombreH.getText(), Double.parseDouble(
                    tf_alturaH.getText()), Integer.parseInt(tf_edadH.getText()), salud, poder));
            All.add(new Hamadriades(salArbol, tf_nombreH.getText(), Double.parseDouble(
                    tf_alturaH.getText()), Integer.parseInt(tf_edadH.getText()), salud, poder));
            JOptionPane.showMessageDialog(null, "Se Guardo Exitosamente");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ha Ocurrido Un Error");
        }
        tf_nombreH.setText("");
        tf_alturaH.setText("");
        tf_edadH.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int salud = 475, poder = 57; 
        try {
            lamia.add(new Lamias(Integer.parseInt(tf_aleta.getText()), 
                Integer.parseInt(tf_branquias.getText()), tf_nombreL.getText(), Double.parseDouble(
                tf_alturaL.getText()), Integer.parseInt(tf_edadL.getText()), 
                salud, poder));
            All.add(new Lamias(Integer.parseInt(tf_aleta.getText()), 
                Integer.parseInt(tf_branquias.getText()), tf_nombreL.getText(), Double.parseDouble(
                tf_alturaL.getText()), Integer.parseInt(tf_edadL.getText()), 
                salud, poder));
            JOptionPane.showMessageDialog(null, "Se Guardo Exitosamente");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ha Ocurrido Un Error");
        }
        tf_nombreL.setText("");
        tf_alturaL.setText("");
        tf_edadL.setText("");
        tf_aleta.setText("");
        tf_branquias.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int salud = 683, poder = 71; 
        try {
            salamandra.add(new Salamandras( Integer.parseInt(tf_alasSS.getText()), 
                tf_nombreSS.getText(), Double.parseDouble(
                tf_alturaSS.getText()), Integer.parseInt(tf_edadSS.getText()), 
                salud, poder));
            All.add(new Salamandras( Integer.parseInt(tf_alasSS.getText()), 
                tf_nombreSS.getText(), Double.parseDouble(
                tf_alturaSS.getText()), Integer.parseInt(tf_edadSS.getText()), 
                salud, poder));
            JOptionPane.showMessageDialog(null, "Se Guardo Exitosamente");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ha Ocurrido Un Error");
        }
        tf_nombreSS.setText("");
        tf_alturaSS.setText("");
        tf_edadSS.setText("");
        tf_alasSS.setText("");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        int salud = 563, poder = 67; 
        try {
            silfide.add(new Silfides(Integer.parseInt(tf_alasS.getText()), tf_nombreS.getText(), Double.parseDouble(
                tf_alturaS.getText()), Integer.parseInt(tf_edadS.getText()), 
                salud, poder));
            All.add(new Silfides(Integer.parseInt(tf_alasS.getText()), tf_nombreS.getText(), Double.parseDouble(
                tf_alturaS.getText()), Integer.parseInt(tf_edadS.getText()), 
                salud, poder));
            JOptionPane.showMessageDialog(null, "Se Guardo Exitosamente");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ha Ocurrido Un Error");
        }
        tf_nombreS.setText("");
        tf_alturaS.setText("");
        tf_edadS.setText("");
        tf_alasS.setText("");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void cb_hadas1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_hadas1ItemStateChanged
        if (cb_hadas.getSelectedIndex() == 0) {
            DefaultListModel modelo = new DefaultListModel();
            for (int i = 0; i < lamia.size(); i++) {
                modelo.addElement(lamia.get(i));
            }
            jl_ElimHadas.setModel(modelo);
        } else if (cb_hadas.getSelectedIndex() == 1) {
            DefaultListModel modelo = new DefaultListModel();
            for (int i = 0; i < hamadriade.size(); i++) {
                modelo.addElement(hamadriade.get(i));
            }
            jl_ElimHadas.setModel(modelo);
        } else if (cb_hadas.getSelectedIndex() == 2) {
            DefaultListModel modelo = new DefaultListModel();
            for (int i = 0; i < silfide.size(); i++) {
                modelo.addElement(silfide.get(i));
            }
            jl_ElimHadas.setModel(modelo);
        } else if (cb_hadas.getSelectedIndex() == 3) {
            DefaultListModel modelo = new DefaultListModel();
            for (int i = 0; i < salamandra.size(); i++) {
                modelo.addElement(salamandra.get(i));
            }
            jl_ElimHadas.setModel(modelo);
        }  else {
            JOptionPane.showMessageDialog(this, "NO SE PUDO");
        }
    }//GEN-LAST:event_cb_hadas1ItemStateChanged

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        int pos = jl_ElimHadas.getSelectedIndex();
        if (jl_ElimHadas.getSelectedIndex() != -1) {
            DefaultListModel modelo = new DefaultListModel();
            lamia.remove(pos);
            for (int i = 0; i < lamia.size(); i++) {
                modelo.addElement(lamia.get(i));
            }
            jl_ElimHadas.setModel(modelo);
        } else
        if (jl_ElimHadas.getSelectedIndex() != -1) {
            DefaultListModel modelo = new DefaultListModel();
            hamadriade.remove(pos);
            for (int i = 0; i < hamadriade.size(); i++) {
                modelo.addElement(hamadriade.get(i));
            }
            jl_ElimHadas.setModel(modelo);
        } else
        if (jl_ElimHadas.getSelectedIndex() != -1) {
            DefaultListModel modelo = new DefaultListModel();
            silfide.remove(pos);
            for (int i = 0; i < silfide.size(); i++) {
                modelo.addElement(silfide.get(i));
            }
            jl_ElimHadas.setModel(modelo);
        } else
        if (jl_ElimHadas.getSelectedIndex() != -1) {
            DefaultListModel modelo = new DefaultListModel();
            salamandra.remove(pos);
            for (int i = 0; i < salamandra.size(); i++) {
                modelo.addElement(salamandra.get(i));
            }
            jl_ElimHadas.setModel(modelo);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jl_modHadasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jl_modHadasValueChanged
        if (cb_hadas.getSelectedIndex() == 0) {
            int postn = cb_hadas.getSelectedIndex();
            if (postn != -1) {
                tf_nombre1.setText(lamia.get(postn).getNombre());
                tf_altura1.setText(lamia.get(postn).getAltura() + "");
                tf_edad1.setText(lamia.get(postn).getEdad() + "");
                tf_aleta1.setText(lamia.get(postn).getAleta() + "");
                tf_branquias1.setText(lamia.get(postn).getBranquias() + "");
                tf_alas1.setText("-NULL-");
                tf_alas1.setEnabled(false);
                tf_aleta1.setEnabled(true);
                tf_branquias1.setEnabled(true);
            } else {
            }
        } else if (cb_hadas.getSelectedIndex() == 1) {
            int postn = cb_hadas.getSelectedIndex();
            if (postn != -1) {
                tf_nombre1.setText(hamadriade.get(postn).getNombre());
                tf_altura1.setText(hamadriade.get(postn).getAltura() + "");
                tf_edad1.setText(hamadriade.get(postn).getEdad() + "");
                tf_alas1.setText("-NULL-");
                tf_alas1.setEnabled(false);
                tf_aleta1.setText("-NULL-");
                tf_aleta1.setEnabled(false);
                tf_branquias1.setText("-NULL-");
                tf_branquias1.setEnabled(false);
            } else {
            }
        } else if (cb_hadas.getSelectedIndex() == 2) {
            int postn = cb_hadas.getSelectedIndex();
            if (postn != -1) {
                tf_nombre1.setText(silfide.get(postn).getNombre());
                tf_altura1.setText(silfide.get(postn).getAltura() + "");
                tf_edad1.setText(silfide.get(postn).getEdad() + "");
                tf_alas1.setText(silfide.get(postn).getAlas() + "");
                tf_alas1.setEnabled(true);
                tf_aleta1.setText("-NULL-");
                tf_aleta1.setEnabled(false);
                tf_branquias1.setText("-NULL-");
                tf_branquias1.setEnabled(false);
            } else {
            }
        } else if (cb_hadas.getSelectedIndex() == 3) {
            int postn = cb_hadas.getSelectedIndex();
            tf_nombre1.setText(salamandra.get(postn).getNombre());
            tf_altura1.setText(salamandra.get(postn).getAltura() + "");
            tf_edad1.setText(salamandra.get(postn).getEdad() + "");
            tf_alas1.setText(salamandra.get(postn).getAlas() + "");
            tf_alas1.setEnabled(true);
            tf_aleta1.setText("-NULL-");
            tf_aleta1.setEnabled(false);
            tf_branquias1.setText("-NULL-");
            tf_branquias1.setEnabled(false);
        }
    }//GEN-LAST:event_jl_modHadasValueChanged

    private void cb_hadasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_hadasItemStateChanged
        if (cb_hadas.getSelectedIndex() == 0) {
            DefaultListModel modelo = new DefaultListModel();
            for (int i = 0; i < lamia.size(); i++) {
                modelo.addElement(lamia.get(i));
            }
            jl_modHadas.setModel(modelo);
        } else if (cb_hadas.getSelectedIndex() == 1) {
            DefaultListModel modelo = new DefaultListModel();
            for (int i = 0; i < hamadriade.size(); i++) {
                modelo.addElement(hamadriade.get(i));
            }
            jl_modHadas.setModel(modelo);
        } else if (cb_hadas.getSelectedIndex() == 2) {
            DefaultListModel modelo = new DefaultListModel();
            for (int i = 0; i < silfide.size(); i++) {
                modelo.addElement(silfide.get(i));
            }
            jl_modHadas.setModel(modelo);
        } else if (cb_hadas.getSelectedIndex() == 3) {
            DefaultListModel modelo = new DefaultListModel();
            for (int i = 0; i < salamandra.size(); i++) {
                modelo.addElement(salamandra.get(i));
            }
            jl_modHadas.setModel(modelo);
        }  else {
            JOptionPane.showMessageDialog(this,"NO SE PUDO");
        }
    }//GEN-LAST:event_cb_hadasItemStateChanged

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        int postn = jl_modHadas.getSelectedIndex();
        if (cb_hadas.getSelectedIndex() == 0) {
            lamia.get(postn).setNombre(tf_nombre1.getText());
            lamia.get(postn).setAltura(Double.parseDouble(tf_altura1.getText()));
            lamia.get(postn).setEdad(Integer.parseInt(tf_edad1.getText()));
            lamia.get(postn).setAleta(Double.parseDouble(tf_aleta1.getText()));
            lamia.get(postn).setBranquias(Integer.parseInt(tf_branquias1.getText()));
            tf_nombre1.setText("");
            tf_altura1.setText("");
            tf_edad1.setText("");
            tf_alas1.setText("");
            tf_alas1.setEnabled(false);
            tf_aleta.setText("");
            tf_aleta.setEnabled(true);
            tf_branquias1.setText("");
            tf_branquias1.setEnabled(true);
        } else if (cb_hadas.getSelectedIndex() == 1) {
            hamadriade.get(postn).setNombre(tf_nombre1.getText());
            hamadriade.get(postn).setAltura(Double.parseDouble(tf_altura1.getText()));
            hamadriade.get(postn).setEdad(Integer.parseInt(tf_edad1.getText()));
            tf_nombre1.setText("");
            tf_altura1.setText("");
            tf_edad1.setText("");
            tf_alas1.setText("");
            tf_alas1.setEnabled(false);
            tf_aleta.setText("");
            tf_aleta.setEnabled(false);
            tf_branquias1.setText("");
            tf_branquias1.setEnabled(false);
        } else if (cb_hadas.getSelectedIndex() == 2) {
            silfide.get(postn).setNombre(tf_nombre1.getText());
            silfide.get(postn).setAltura(Double.parseDouble(tf_altura1.getText()));
            silfide.get(postn).setEdad(Integer.parseInt(tf_edad1.getText()));
            silfide.get(postn).setAlas(Integer.parseInt(tf_alas1.getText()));
            tf_nombre1.setText("");
            tf_altura1.setText("");
            tf_edad1.setText("");
            tf_alas1.setText("");
            tf_alas1.setEnabled(true);
            tf_aleta.setText("");
            tf_aleta.setEnabled(false);
            tf_branquias1.setText("");
            tf_branquias1.setEnabled(false);
        } else if (cb_hadas.getSelectedIndex() == 3) {
            salamandra.get(postn).setNombre(tf_nombre1.getText());
            salamandra.get(postn).setAltura(Double.parseDouble(tf_altura1.getText()));
            salamandra.get(postn).setEdad(Integer.parseInt(tf_edad1.getText()));
            salamandra.get(postn).setAlas(Integer.parseInt(tf_alas1.getText()));
            tf_nombre1.setText("");
            tf_altura1.setText("");
            tf_edad1.setText("");
            tf_alas1.setText("");
            tf_alas1.setEnabled(true);
            tf_aleta.setText("");
            tf_aleta.setEnabled(false);
            tf_branquias1.setText("");
            tf_branquias1.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(this, "Ha Fallado");
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        if (cont == 0) {
            JFileChooser jfc = new JFileChooser();
            int seleccion = jfc.showSaveDialog(this);
            if (seleccion == JFileChooser.APPROVE_OPTION) {
                direccion = jfc.getSelectedFile();
            }
            cont++;
        }
        try {
            FileOutputStream hadastxt = new FileOutputStream(direccion);
            ObjectOutputStream oos = new ObjectOutputStream(hadastxt);

            oos.writeObject(lamia);
            oos.writeObject(hamadriade);
            oos.writeObject(silfide);
            oos.writeObject(salamandra);

            oos.close();
            hadastxt.close();
            System.out.println("Saved........");
            JOptionPane.showMessageDialog(null, "guardado con exito");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        if (cont != 0) {
            JFileChooser jfc = new JFileChooser();
            int seleccion = jfc.showSaveDialog(this);
            if (seleccion == JFileChooser.APPROVE_OPTION) {
                direccion = jfc.getSelectedFile();
            }
            cont++;
        }
        try {
            FileOutputStream hadastxt = new FileOutputStream(direccion);
            ObjectOutputStream oos = new ObjectOutputStream(hadastxt);

            oos.writeObject(lamia);
            oos.writeObject(hamadriade);
            oos.writeObject(silfide);
            oos.writeObject(salamandra);

            oos.close();
            hadastxt.close();
            System.out.println("SAVED.......");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JFileChooser jfc = new JFileChooser();
        int seleccion = jfc.showOpenDialog(this);
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            direccion = jfc.getSelectedFile();
        }
        cont++;
        try {
            FileInputStream entrada = new FileInputStream(direccion);
            ObjectInputStream objeto = new ObjectInputStream(entrada);

            lamia = (ArrayList<Lamias>) objeto.readObject();
            hamadriade = (ArrayList<Hamadriades>) objeto.readObject();
            silfide = (ArrayList<Silfides>) objeto.readObject();
            salamandra = (ArrayList<Salamandras>) objeto.readObject();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        JOptionPane.showMessageDialog(this, "Pelea de Hadas\n"+"Version 6.6.6\n"
                + "Compiled Marzo 17 2017 5:38:34\n"
                + "Author: Haslin Avila\n"
                + "\n"
                + "Pelea de Hadas v_1.5\n"
                + "\n"
                + "Mac y Windows son marcas Propias de otras\n"
                + "compañias. no nos hacemos responsables por VIRUS\n"
                + "No estan asociadas con Land of Fairies");
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        AdminPelea ap1 = new AdminPelea();
        AdminPelea ap2 = new AdminPelea();
        
        if (ap1.getFairy1() instanceof Lamias && ap2.getFairy2() instanceof Silfides){
            ap1 = new AdminPelea(pb_player1, pb_player2, (Hadas)cb_hada1.getSelectedItem(), (Hadas)cb_hada2.getSelectedItem());
            ap2 = new AdminPelea(pb_player1, pb_player2, (Hadas)cb_hada1.getSelectedItem(), (Hadas)cb_hada2.getSelectedItem());
            ap1.start();
            ap2.start();
        } 
        if (ap1.getFairy1() instanceof Hamadriades && ap2.getFairy2() instanceof Salamandras){
            ap1 = new AdminPelea(pb_player1, pb_player2, (Hadas)cb_hada1.getSelectedItem(), (Hadas)cb_hada2.getSelectedItem());
            ap2 = new AdminPelea(pb_player1, pb_player2, (Hadas)cb_hada1.getSelectedItem(), (Hadas)cb_hada2.getSelectedItem());
            ap1.start();
            ap2.start();
        } 
        if (ap1.getFairy1() instanceof Salamandras && ap2.getFairy2() instanceof Silfides){
            ap1 = new AdminPelea(pb_player1, pb_player2, (Hadas)cb_hada1.getSelectedItem(), (Hadas)cb_hada2.getSelectedItem());
            ap2 = new AdminPelea(pb_player1, pb_player2, (Hadas)cb_hada1.getSelectedItem(), (Hadas)cb_hada2.getSelectedItem());
            ap1.start();
            ap2.start();
        } 
        if (ap1.getFairy1() instanceof Lamias && ap2.getFairy2() instanceof Hamadriades){
            ap1 = new AdminPelea(pb_player1, pb_player2, (Hadas)cb_hada1.getSelectedItem(), (Hadas)cb_hada2.getSelectedItem());
            ap2 = new AdminPelea(pb_player1, pb_player2, (Hadas)cb_hada1.getSelectedItem(), (Hadas)cb_hada2.getSelectedItem());
            ap1.start();
            ap2.start();
        }
            if (ap1.getFairy1() instanceof Silfides && ap2.getFairy2() instanceof Hamadriades){
            ap1 = new AdminPelea(pb_player1, pb_player2, (Hadas)cb_hada1.getSelectedItem(), (Hadas)cb_hada2.getSelectedItem());
            ap2 = new AdminPelea(pb_player1, pb_player2, (Hadas)cb_hada1.getSelectedItem(), (Hadas)cb_hada2.getSelectedItem());
            ap1.start();
            ap2.start();
        }
        if (ap1.getFairy1() instanceof Salamandras && ap2.getFairy2() instanceof Lamias){
            ap1 = new AdminPelea(pb_player1, pb_player2, (Hadas)cb_hada1.getSelectedItem(), (Hadas)cb_hada2.getSelectedItem());
            ap2 = new AdminPelea(pb_player1, pb_player2, (Hadas)cb_hada1.getSelectedItem(), (Hadas)cb_hada2.getSelectedItem());
            ap1.start();
            ap2.start();
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jButton1StateChanged
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        for (int i = 0; i < All.size(); i++) {
            modelo.addElement(((Hadas)All.get(i)));
        }
        cb_hada1.setModel(modelo);
    }//GEN-LAST:event_jButton1StateChanged

    private void jButton1StateChanged2(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jButton1StateChanged2
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        for (int i = 0; i < All.size(); i++) {
            modelo.addElement(((Hadas)All.get(i)));
        }
        cb_hada2.setModel(modelo);
    }//GEN-LAST:event_jButton1StateChanged2

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog AgregarEM;
    private javax.swing.JDialog Simulacion;
    private javax.swing.JComboBox<String> cb_hada1;
    private javax.swing.JComboBox<String> cb_hada2;
    private javax.swing.JComboBox cb_hadas;
    private javax.swing.JComboBox cb_hadas1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JList<String> jl_ElimHadas;
    private javax.swing.JList jl_modHadas;
    private javax.swing.JProgressBar pb_player1;
    private javax.swing.JProgressBar pb_player2;
    private javax.swing.JTextField tf_alas1;
    private javax.swing.JTextField tf_alasS;
    private javax.swing.JTextField tf_alasSS;
    private javax.swing.JTextField tf_aleta;
    private javax.swing.JTextField tf_aleta1;
    private javax.swing.JTextField tf_altura1;
    private javax.swing.JTextField tf_alturaH;
    private javax.swing.JTextField tf_alturaL;
    private javax.swing.JTextField tf_alturaS;
    private javax.swing.JTextField tf_alturaSS;
    private javax.swing.JTextField tf_branquias;
    private javax.swing.JTextField tf_branquias1;
    private javax.swing.JTextField tf_edad1;
    private javax.swing.JTextField tf_edadH;
    private javax.swing.JTextField tf_edadL;
    private javax.swing.JTextField tf_edadS;
    private javax.swing.JTextField tf_edadSS;
    private javax.swing.JTextField tf_nombre1;
    private javax.swing.JTextField tf_nombreH;
    private javax.swing.JTextField tf_nombreL;
    private javax.swing.JTextField tf_nombreS;
    private javax.swing.JTextField tf_nombreSS;
    private javax.swing.JTextField tf_poderH;
    private javax.swing.JTextField tf_poderL;
    private javax.swing.JTextField tf_poderS;
    private javax.swing.JTextField tf_poderSS;
    private javax.swing.JTextField tf_salarbolH;
    private javax.swing.JTextField tf_saludH;
    private javax.swing.JTextField tf_saludL;
    private javax.swing.JTextField tf_saludS;
    private javax.swing.JTextField tf_saludSS;
    // End of variables declaration//GEN-END:variables
ArrayList<Lamias> lamia = new ArrayList();
ArrayList<Hamadriades> hamadriade = new ArrayList();
ArrayList<Silfides> silfide = new ArrayList();
ArrayList<Salamandras> salamandra = new ArrayList();
ArrayList All = new ArrayList();
File direccion = null;
int cont;

}
